(async () => {
    
})().catch(e => {
    console.error(e);
    process.exit(1);
});
